name: 'Build and publish docker image (arm32 platform)'

on:
  workflow_dispatch:
  push:
    branches:
      #- '**'       # matches every branch
      - 'master'  # excludes master
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: lenuswalker/expressvpn  # list of Docker images to use as base name for tags
          flavor: |
            latest=false
            prefix=
            surfix=-armhf
          tags: |
            type=ref,event=branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2 
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PLATFORM=armhf
            NUM=3.10.0.9
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}