name: 'Build and publish docker image (amd64 platform)'

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'  # excludes master
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: lenuswalker/expressvpn  # list of Docker images to use as base name for tags
          flavor: |
            latest=false
            prefix=github-workflow-
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-,format=short
            type=ref,event=branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ github.repository }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push latest
        uses: docker/build-push-action@v2
        if: steps.git.outputs.tag == 'true'
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.3
        if: steps.git.outputs.tag == 'true'
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}