name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --build-arg NUM=3.10.0.9 --build-arg --platform linux/amd64,linux/arm64,linux/arm/v7 .
