name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --build-arg NUM=3.10.0.9 --build-arg PLATFORM=arm64v8 --platform linux/arm64/v8 --tag lenuswalker/expressvpn:arm64v8 .
